build: add nlohmann::json library & -fno-rtti flag
The `nlohmann/json` library is connected to the project; added
`-fno-rtti` flag to MinGW / Clang builds because of the `libstdc++` bug (see below).

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110572:
   ld.lld: error: duplicate symbol: std::type_info::operator==(std::type_info const&) const
Signed-off-by: Dmitry Lyubimcev <dzone@danwin1210.de>